AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs16.x
Resources:
  ImageAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.imageAnalysis
      Runtime: nodejs20.x
      Environment:
        Variables:
          FIXED_WIDTH_BUCKET: cb-face-photo-bucket-aws-sam-version
          NODE_ENV: production
      Events:
        S3PhotoUploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: FixedWidthBucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .png
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:*
          Resource: '*'
        - Effect: Allow
          Action:
          - rekognition:*
          Resource: '*'
      CodeUri: s3://aws-sam-demo-staging-area/4362b100acc778c18d2354e396611389
    Metadata:
      SamResourceId: ImageAnalysisFunction
  FixedWidthBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cb-face-photo-bucket-aws-sam-version
    Metadata:
      SamResourceId: FixedWidthBucket
