AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs16.x

Resources:
  ImageAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.imageAnalysisAwsSam
      Runtime: nodejs16.x
      Environment:
        Variables:
          FIXED_WIDTH_BUCKET: 'cb-face-photo-bucket-aws-sam-version'
          NODE_ENV: production
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref FixedWidthBucket
            Events: s3:ObjectCreated:*
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"
            - Effect: Allow
              Action:
                - rekognition:*
              Resource: "*"

  FixedWidthBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'cb-face-photo-bucket-aws-sam-version'

  BucketPermission:
    Type: AWS::Lambda::Permission
    DependsOn: FixedWidthBucket
    Properties:
      FunctionName: !Ref ImageAnalysisFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::cb-face-photo-bucket-aws-sam-version